# Generated by Django 5.1.1 on 2024-11-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0005_product_likes_count_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
