# Generated by Django 5.1.1 on 2024-11-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0011_product_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
