# Generated by Django 5.1.1 on 2024-11-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0012_remove_product_likes_count_remove_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
