# Generated by Django 5.1.1 on 2024-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0014_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XXL', 'XXL'), ('XL', 'XL'), ('XXXL', 'XXXL')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XXL', 'XXL'), ('XL', 'XL'), ('XXXL', 'XXXL')], max_length=5),
        ),
    ]
