# Generated by Django 5.1.1 on 2024-11-28 09:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0015_alter_cart_size_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XXL', 'XXL'), ('XL', 'XL'), ('XXXL', 'XXXL')], max_length=17),
        ),
    ]
