# Generated by Django 5.1.1 on 2024-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0016_remove_product_ratings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
